[theme]
primaryColor = "#009c3b"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#333333"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false
